# Generated by Django 5.0.4 on 2024-07-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_author_posts_post_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posts',
            new_name='author',
        ),
    ]
